name: Deploy VuePress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build VuePress site
        run: npm run docs:build
      - name: Deploy to Server
        run: |
          $env:USERPROFILE = [System.Environment]::GetEnvironmentVariable('USERPROFILE')
          $sshDir = "$env:USERPROFILE\.ssh"
          New-Item -ItemType Directory -Force -Path $sshDir
          $privateKeyPath = "$sshDir\id_rsa"
          Set-Content -Path $privateKeyPath -Value "${{ secrets.SSH_PRIVATE_KEY }}"
          icacls $privateKeyPath /inheritance:r
          icacls $privateKeyPath /grant:r "$($env:USERNAME):(R)"
          icacls $privateKeyPath /grant:r "$($env:USERNAME):(W)"
          icacls $privateKeyPath /grant:r "Administrators:(R)"
          icacls $privateKeyPath /remove "Users"
          Start-Service ssh-agent
          ssh-add $privateKeyPath
          if ('${{ secrets.DEPLOY_PASSPHRASE }}' -ne '') {
            ssh-add -p "${{ secrets.DEPLOY_PASSPHRASE }}"
          }
          scp -r E:\桌面\Projects\codefather-template\codefather-template\.vuepress\dist\* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_DIR }}

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_PASSPHRASE: ${{ secrets.DEPLOY_PASSPHRASE }}
