name: Deploy VuePress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build VuePress site
        run: npm run docs:build
      - name: Deploy to Server
        run: |
          SET USERPROFILE=%USERPROFILE%
          mkdir "%USERPROFILE%\.ssh"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > "%USERPROFILE%\.ssh\id_rsa"
         icacls "%USERPROFILE%\.ssh\id_rsa" /grant:r "%USERPROFILE%:(rw)"
          
          # 如果您的环境不需要修改密码或已经有合适的权限，则下面两行可以省略
          ssh-keygen -p -f "%USERPROFILE%\.ssh\id_rsa" -P "" -N "$DEPLOY_PASSPHRASE"

          # 使用scp命令同步文件
          scp -r ./vuepress/dist/* "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_PASSPHRASE: ${{ secrets.DEPLOY_PASSPHRASE }}
