name: Deploy VuePress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build VuePress site
        run: npm run docs:ubuild

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          #scp参数
          ARGS: "-avzr --delete"
          #源目录
          SOURCE: "/.vuepress/dist/"
          #服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          #用户
          REMOTE_USER: "root"
          #目标地址
          TARGET: "/var/www/codefather/dist"
